### ISSUE TITLE
Initiative: G0.8 v0.2 dogfood hardening — make the shipped v0.2 actually consumer-usable

### ISSUE THREAD

**Issue by damir-topic** [evoila/meho#634]
Parent goal: #221

## Scope

Make the **shipped, tagged, deployed v0.2 actually usable by the consumer
team.** v0.2.0 is tagged and live (acceptance smoke green), but seven
independent dogfood signals from the consumer team prove the smoke-green
is hollow: the acceptance smoke passes because `dry_run` ingests never
write, so the foundational FK wall (#628) stays invisible until the first
*real* write — and a fresh runbook-following deploy can do **zero**
tenant-scoped writes. Read together, the seven signals say an operator
who follows the published runbooks to the letter cannot complete a single
real workflow on v0.2.

This Initiative parents the seven existing signal issues as child Tasks,
fixes each at the root (not via consumer-side workarounds), and gates a
clean-room re-verification that a fresh v0.2 deploy can do real work. It
is **slotted ahead of v0.3** in the MVP roadmap: there is no value
shipping MVP2 on top of an MVP1 the consumer cannot write to.

## Why this is one Initiative, not seven loose issues

All seven share one root condition: v0.2 was tagged on a smoke suite that
exercises only non-writing / non-federated paths. They are the corrective
for that gap as a unit, and three of them hard-block each other's
verification (you cannot re-verify the deploy end-to-end until #628, #583,
and #629 all clear). Comparable hardening-as-one-Initiative precedent in
this repo: the G0 substrate Initiatives (#222–#389) were grouped under one
Goal for exactly this "shared foundational invariant" reason.

## Freeze

While the three hard blockers **#628 / #583 / #629** are open, no new
v0.3/v0.4 Initiative *starts*. The v0.4 ownership already assigned holds
but does not begin: #368 (@kr3s0), #374 + #332 (@ikaric), #375
(@ddzafic). The freeze lifts per-track as each blocker closes.

## Corrective note on mis-stated parents (no surgery)

- **#628** exposes that G0.1 tenant model (#222, board state "Done")
  shipped with no tenant-provisioning path —
  `backend/alembic/versions/0002_create_tenant_and_audit_tenant_id.py:40-62`
  explicitly defers seeding and blesses ad-hoc PG inserts as the v0.2
  mechanism; `backend/src/meho_backplane/auth/jwt.py:356-384`
  (`_extract_tenant_id`) only lifts `tenant_id` from the JWT, with no
  ensure-tenant anywhere in the request path.
- **#629** exposes that G3.3 vault (#366, board state "Closed") shipped a
  connector that cannot execute against a real G0.3 target —
  `backend/src/meho_backplane/connectors/vault/connector.py:88-98` is a
  pre-#224 stub `VaultTarget` with `raw_jwt`;
  `backend/src/meho_backplane/targets/schemas.py:75-112` (the real
  targets-as-data `Target`) has no such field.

#222 and #366 are **factually mis-stated as complete** on the board. The
corrective is this Initiative and its DoD — **not** re-opening or
re-scoping those closed parents (explicitly out of scope below).

## Work items grouped under this Initiative

Each child Task originated as an already-filed consumer dogfood signal
issue, converted in place under this Initiative and (during the G0.8
`/review-ticket` pass) brought to full Task-template conformance with
codebase-verified `file:line` grounding. Each child preserves a
**Root cause (consumer-supplied, codebase-verified)** section so the
upstream signal stays traceable. All seven assigned to **@damir-topic**.

1. **#628 (G0.8-T1) — empty tenant table, every tenant-scoped write
   FK-fails.** Ship a **minimal** v0.2 tenant-seed path (ensure-tenant on
   the authenticated request path, keyed to the JWT `tenant_id` claim).
   Bar: a runbook-following deploy does not hit an asyncpg FK traceback
   on its first real write. **Hard blocker.**
2. **#583 (G0.8-T2) — chart `REDIS_URL` vs backplane
   `BROADCAST_REDIS_URL`.** Align the chart env-var name so `/ready`'s
   broadcast leg succeeds and `helm upgrade` does not roll back. **Hard
   blocker.**
3. **#629 (G0.8-T3) — vault connector pre-#224 `raw_jwt` stub.** Read
   the operator JWT from request-scoped `Operator` context; drop the
   stub `VaultTarget`. **Hard blocker.**
4. **#633 (G0.8-T4) — `MCP_RESOURCE_URI` default doesn't apply →
   unactionable 401.** Chart-derived default or fail-loud at startup;
   enrich the `audience_not_configured` 401 detail.
5. **#630 (G0.8-T5) — `connector_id` undocumented + empty-200 trap.**
   Document the `<impl_id>-<version>` format; 404 on unknown connector.
6. **#632 (G0.8-T6) — retrieve/usage counted-surface undocumented.**
   Document which surface feeds the counter; make the REST-excluded
   zero non-silent.
7. **#631 (G0.8-T7) — `/version` returns `unknown/unknown/null`.**
   Pass Docker build-args in `image.yml`; surface `.Chart.Version` as
   env; `version.py` reads it.

## Definition of done

- [ ] Clean-room v0.2 deploy following only the published runbooks: the
      first real (non-dry-run) `POST /api/v1/kb/ingest` **succeeds** — no
      `documents_tenant_id_fkey` violation (#628).
- [ ] `helm upgrade` on a healthy Valkey completes without rollback;
      `/ready` broadcast leg reports `ok` (#583).
- [ ] `operations/call` against a registered vault target returns a
      success envelope, not `'Target' object has no attribute 'raw_jwt'`
      (#629).
- [ ] On a deploy without `BACKPLANE_URL`, `/mcp` is reachable via a
      chart-derived default **or** startup fails loudly with the
      remediation; the 401 body links `mcp-client-setup.md` (#633).
- [ ] `GET /api/v1/operations/groups` with an unknown `connector_id`
      returns 404/422; the OpenAPI param documents `<impl_id>-<version>`
      (#630).
- [ ] Docs (or the API responses) state which surface feeds
      `retrieve/usage`; REST-only dogfooding no longer shows a silent
      zero for a month (#632).
- [ ] `GET /version` on the next shipped image returns real `git_sha` +
      `build_date` + `chart_version` (#631).
- [ ] `docs/planning/mvp-roadmap.md` updated to slot **G0.8 ahead of
      v0.3**; the `/meho-status` skill's hardcoded `VERSION_MAP` is
      flagged as drifted-from-doc (NOT silently edited — surfaced to the
      maintainer per that skill's hard rule 7).
- [ ] Goal #221 body checklist gains a **G0.8** line and it is ticked.
- [ ] All 7 child Tasks closed; CI green on each; the v0.2 acceptance
      smoke is extended to exercise one real (non-dry-run, federated)
      write so this class of "green-but-hollow" cannot recur.

## Out of scope

- **Full tenant-provisioning REST API** (create/list/delete tenants with
  RBAC) — v0.3+. #628's bar is a minimal seed path only.
- **Re-opening or re-scoping #222 (G0.1) or #366 (G3.3).** They are
  factually mis-stated as complete; the corrective is this Initiative +
  its DoD, not surgery on closed parents.
- **New connectors, memory work, topology, UI** — frozen, not in scope
  here.
- **Editing the `/meho-status` skill's `VERSION_MAP`** — that skill's
  hard rule 7 makes the roadmap doc canonical; drift is surfaced, not
  silently reconciled here.

## References

- Parent Goal: [#221](https://github.com/evoila/meho/issues/221) G0
  Foundational substrate (this Initiative is its corrective —
  `## Execution Initiatives` checklist carries the unticked G0.8 line).
- Mis-stated parents: [#222](https://github.com/evoila/meho/issues/222)
  G0.1 tenant model, [#366](https://github.com/evoila/meho/issues/366)
  G3.3 vault — corrective only, no surgery (see Out of scope).
- Codebase-verified roots (this session, branch `main` @ b5de86d):
  `backend/alembic/versions/0002_create_tenant_and_audit_tenant_id.py:40-62`,
  `backend/src/meho_backplane/auth/jwt.py:356-384,489-490`,
  `backend/src/meho_backplane/connectors/vault/connector.py:88-98`,
  `backend/src/meho_backplane/targets/schemas.py:75-112`,
  `backend/src/meho_backplane/api/v1/operations.py:66,80`,
  `backend/src/meho_backplane/operations/meta_tools.py:229-232`,
  `backend/src/meho_backplane/retrieval/usage.py:151-154,325-356`,
  `backend/src/meho_backplane/api/v1/retrieve.py:155-205`,
  `backend/src/meho_backplane/version.py:44-46`,
  `backend/Dockerfile:96-115`, `.github/workflows/image.yml:168-178`,
  `.github/workflows/chart.yml:836-863`,
  `deploy/charts/meho/templates/deployment.yaml:62`,
  `backend/src/meho_backplane/settings.py:305,436-438`,
  `backend/src/meho_backplane/mcp/auth.py:97-101`,
  `backend/src/meho_backplane/broadcast/client.py:75`.
- Roadmap canonical source: `docs/planning/mvp-roadmap.md` (drives the
  hardcoded `/meho-status` `VERSION_MAP`; drift surfaced not edited).
- Best-practices anchors (per child surface): Python best-practices
  pack (T1/T3/T5/T6), DevOps best-practices pack (T2/T7), Python +
  DevOps (T4) — cited by pack name; the repo ships only `-slim` skills
  so anchor file paths are dead.

## Child Tasks (filed)

- [ ] #628 — G0.8-T1 tenant-row seed on first authenticated write — **blocker**
- [ ] #583 — G0.8-T2 chart Valkey env-var alignment — **blocker**
- [ ] #629 — G0.8-T3 vault connector operator-JWT from request context — **blocker**
- [ ] #633 — G0.8-T4 MCP_RESOURCE_URI default / fail-loud
- [ ] #630 — G0.8-T5 connector_id docs + 404-on-unknown
- [ ] #632 — G0.8-T6 retrieve/usage counted-surface docs
- [ ] #631 — G0.8-T7 /version build stamping
- [ ] #668 — G0.8-T8 acceptance test: real federated `POST /operations/call` (vault) through `verify_jwt_and_bind` — v0.2.1 gate

**Comment by damir-topic** [comment]
## /auto-implement-initiative run summary

2026-05-18 — all 7 child Tasks implemented, Claude-reviewed (APPROVE, 0 blockers), and **merged**. 0 auto-parked.

**Merged** (auto-closed on merge):

| Task | PR | Review iterations |
|---|---|---|
| #583 — G0.8-T2 chart Valkey env var | #638 | 1 |
| #628 — G0.8-T1 tenant-row JIT seed (hard blocker) | #639 | 2 (slug-collision + runbook wording) |
| #629 — G0.8-T3 vault operator-JWT from request ctx (hard blocker) | #641 | 1 |
| #630 — G0.8-T5 connector_id docs + 404-on-unknown | #649 | 2 (cross-tenant existence scoping) |
| #631 — G0.8-T7 /version build stamping | #648 | 1 |
| #632 — G0.8-T6 retrieve/usage counted-surface docs | #647 | 2 (docstring contradiction) |
| #633 — G0.8-T4 MCP_RESOURCE_URI default / fail-loud | #652 | 1 (+ manual main-merge conflict resolution in `chart.yml`: kept both the #633 ingress-derivation greps and the #631 CHART_VERSION assert step) |

**Notable adjacent findings recorded during the run (candidates for follow-up tickets, not actioned — out of each task's scope):**
- The MCP authenticated-write path (`verify_mcp_jwt_and_bind` → `add_to_knowledge`) does **not** call `ensure_tenant`, so an MCP-first real write on a fresh deploy can still hit `documents_tenant_id_fkey`. #628's DoD is scoped to the REST `/api/v1/kb/ingest` path; the MCP front door needs the same JIT-seed guarantee.
- `operations/.../ops.py` carries pre-existing >600-line size debt (suppressed via the established `# code-quality-allow` convention during #629); a module split is a separate refactor.

**Remaining Initiative-level DoD (NOT child Tasks — human decision, Initiative stays open):**
- Clean-room v0.2 re-verification (first real non-dry-run `POST /kb/ingest` succeeds; `helm upgrade` on healthy Valkey; vault `operations/call` success envelope; MCP reachable / fail-loud).
- MVP roadmap doc: slot G0.8 ahead of v0.3; flag the `/meho-status` `VERSION_MAP` as drifted (surface, do not silently edit — that skill's hard rule 7).
- Goal #221 body checklist: add + tick a G0.8 line.
- Extend the v0.2 acceptance smoke with one real (non-dry-run, federated) write so "green-but-hollow" cannot recur.

This Initiative is intentionally left **open** — its DoD exceeds the child Tasks.

**Comment by damir-topic** [comment]
## v0.2.1 shipped — G0.8 dogfood-hardening corrective released

**Released:** https://github.com/evoila/meho/releases/tag/v0.2.1 (cut from `main` @ `2fb5893`).

All 7 child Tasks of this Initiative + the acceptance guard (#668) are merged and shipped:
#628 #583 #629 #633 #630 #632 #631 #668. Image `ghcr.io/evoila/meho:v0.2.1`, chart `oci://ghcr.io/evoila/meho-chart:0.2.1`, signed CLI tarballs.

v0.2 release gate green on the tagged commit (`Python ruff+mypy+pytest`, `Go`, `Helm`, `chart`, `image`). Three pre-existing non-v0.2 CI-unbreak fixes also landed while stabilising the lane: #671, #672, #675.

**This Initiative stays OPEN** — its DoD exceeds the shipped child Tasks. Remaining (human-owned):
- Live-cluster clean-room v0.2 re-verification (deferred by maintainer).
- MVP-roadmap G0.8-ahead-of-v0.3 slotting + `/meho-status` VERSION_MAP drift flag.
- Goal #221 checklist G0.8 line.

**Known issue, tracked separately (not a v0.2.1 regression):** the `integration testcontainers` lane's sole failure is the pre-existing G9.2 `test_topology_annotate` flake — tracked in #673, explicitly excluded from the v0.2.1 gate.

**Comment by damir-topic** [comment]
Closing the loop from the consumer side: we repinned our lab off the pre-release `sha-aaa1cd4` pin onto v0.2.1 today and re-ran the exact things that broke during the original dogfood. All seven hold on real infrastructure.

The part worth reporting: the two deploy-side workarounds we'd been carrying — the `BROADCAST_REDIS_URL` extraEnv (#583) and the `MCP_RESOURCE_URI` extraEnv (#633) — we *deleted both*, because the v0.2.1 chart sets them itself now. That deletion was the actual test. If the chart wiring weren't right, `/ready`'s broadcast leg goes red the moment the override is gone. It stayed green. And the new fail-loud MCP-audience guard from #633 means the pod simply reaching `ready` is itself the proof the audience resolved — the old build sat there silently 401-ing every agent call.

#629 was the one I was most curious about. `operations/call vault.kv.read` against a registered target now returns `status: ok` with a real KV-v2 body — that exact call used to throw `'Target' object has no attribute 'raw_jwt'`. I also ran `vault.sys.mounts.list` and got a clean `permission denied` straight from Vault, which is the *correct* outcome: the connector authenticated, called Vault properly, and Vault enforced our deliberately-narrow policy. The governed path works end to end.

#628 (tenant JIT-seed), #631 (real `/version`), #630 (`connector_id`) all check out; DB migrated cleanly on the upgrade.

One thing that was *our* bug, not yours, but might be worth a heads-up for anyone writing acceptance checks: our smoke script had quietly assumed image tags always embed the git-sha (every build we'd deployed was a CI snapshot). The first proper semver tag (`v0.2.1`) doesn't, so our own check false-failed on the first green deploy — latent for weeks, surfaced only because things finally went right. Fixed our side; flagging the pattern in case the upstream smoke doc wants a note.

Thanks for fixing these at the root rather than papering over them — the #668 acceptance guard especially. From the first-deployer seat this is exactly the right shape.

**Comment by damir-topic** [comment]
DoD-verified and closed. All 8 child Tasks closed (T1-T7 fixes #628/#583/#629/#633/#630/#632/#631 + T8 acceptance #668 extending the v0.2 smoke to a real federated non-dry-run write). Final DoD item landed: `docs/planning/mvp-roadmap.md` now slots **v0.2.1 / G0.8 ahead of v0.3** (PR #688, merged 2026-05-19, sha ab22c1cf0) with the `/meho-status` VERSION_MAP-drift surfaced in-doc per hard rule 7 (not silently reconciled). Goal #221 G0.8 line ticked. The three hard blockers (#628/#583/#629) cleared — the v0.3/v0.4 freeze is fully lifted.
