### PR TITLE
fix(ci): restore main CI green — Go gofmt/revive (G9.2 CLI) + k8s e2e meta-tool target contract (#580)

### PR DESCRIPTION
**Pull request by damir-topic**
## Summary

`evoila/meho` `main` was red on two CI jobs, blocking a clean v0.2.1 tag. This is a direct, un-ticketed CI-unbreak: two deterministic regressions that landed on `main` (the DCO admin-bypass is what let them through — this PR ships a real `Signed-off-by` trailer so it passes DCO without a bypass, deliberately). Two separate commits, one per regression.

### Regression 1 — Go (`golangci-lint` job), trivial hygiene

The `Go (golangci-lint + go test)` job (golangci-lint **v1.64.8** / Go **1.23**, `run --path-prefix=cli`) failed on three findings introduced by **#656 (G9.2-T6)** and **#667 (G9.2-T8)**:

- `cli/internal/cmd/topology/list_edges.go:85` — `revive` `unused-parameter`: the cobra `RunE` closure declared `args` but never used it. Renamed `args` → `_` (matches the package convention: siblings that don't consume positional args use `_`; the ones that do use `args[0]`).
- `cli/internal/cmd/topology/bulk_import.go:89` — `gofmt`: doc-comment + struct-tag alignment.
- `cli/internal/cmd/topology/e2e_test.go:403` — `gofmt`: struct-literal field alignment.

Formatting + the one parameter rename only — **no behavioral change**.

### Regression 2 — Python (`Python (integration testcontainers)` job): k8s e2e meta-tool target contract (#580)

`backend/tests/integration/test_connectors_k8s_e2e.py::test_call_operation_about_dispatches_through_meta_tool` failed deterministically:

```
AttributeError: '_K3sTarget' object has no attribute 'get'
  at backend/src/meho_backplane/operations/meta_tools.py:455
```

**Root cause:** since **#438 (G0.6-T8)** the `call_operation` meta-tool requires `arguments["target"]` to be a dict `{"name": <str>}` and resolves it through the tenant-scoped `resolve_target()` (`backend/src/meho_backplane/targets/resolver.py`) before dispatch. That name→`resolve_target` step is the meta-tool's tenant-isolation boundary. The test (last touched by **#580, G3.2-T6**) passed the raw duck-typed `_K3sTarget` **object** as `"target"`; `meta_tools.py:455` does `target_arg.get("name")` on it → `AttributeError`. The `k8s_e2e` fixture preseeded the dispatcher's connector-instance cache but never inserted a `Target` ORM row.

**Fix (option A — test/fixture only):** the `k8s_e2e` fixture now seeds a tenant-scoped `Target` ORM row (`name="k3s-e2e"`, `tenant_id` = the `_make_operator` default tenant, `product="k8s"`, `fingerprint={"version":"1.32.0"}`, host/port/secret_ref mirroring the `_K3sTarget` stub) and deletes it on teardown (`pg_engine` does not truncate the soft-FK `targets` table). The meta-tool test now passes `"target": {"name": "k3s-e2e"}` and pins its operator to the same tenant so `resolve_target` succeeds; the dispatcher still resolves `KubernetesConnector` via the preseeded instance cache, so host/port never reach a real cluster. The other suites keep calling `dispatch()` directly with the duck-typed object — that low-level path legitimately accepts it; only the meta-tool enforces the name→`resolve_target` contract.

**Option B was NOT used.** `meta_tools.py` was not weakened to accept an already-resolved object or `getattr` off non-dicts — that would bypass the tenant-isolation boundary and is a security regression. The handler contract is correct; the test was wrong.

## Test plan

- **Go** — verified with the **CI-exact** golangci-lint **v1.64.8** built on Go 1.23, `run --path-prefix=cli`: clean (exit 0) with the fix; reproduces exactly the three reported findings on clean `main`. `gofmt -l` empty. `go build ./...` clean. `go test ./...` all green (incl. the `topology` package).
- **Python** — `uv run ruff check src/ tests/`, `uv run ruff format --check src/ tests/`, `uv run mypy src/` all clean (no `src/` changes — confirming option B was not taken).
- **k3d integration test** — needs Docker + k3d; CI runs it in the `Python (integration testcontainers)` job. This is the accepted verification path for that test (not locally runnable in the sandbox by design). This environment happened to have Docker available, so the full round-trip (fixture seed → `resolve_target` → dispatcher → live k3s) was exercised end-to-end and **passes**; on clean `main` the full file is `2 failed`, with the fix it is `1 failed` and the previously-targeted test now passes.

### Note: a separate pre-existing flake (out of scope)

`test_dispatch_logs_against_running_pod` (a `k8s.logs` / pod-log timing race on the **direct-`dispatch`** path, unrelated to the meta-tool target contract) is **also red on clean `main`** in the full-file run and is **not** caused by this change (it passes in isolation; it's a freshly-booted-k3s log-availability race). It is not one of the two assigned CI regressions and is intentionally not touched here (surgical-changes discipline). Flagging it for a separate follow-up.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

## Summary by CodeRabbit

* **Tests**
  * Enhanced Kubernetes integration testing infrastructure with improved test fixtures to more thoroughly exercise target resolution and verify proper tenant isolation behavior.

* **Refactor**
  * Removed unused code parameters from command handlers.
  * Improved code formatting and field alignment for better readability.

[Review Change Stack](https://app.coderabbit.ai/change-stack/evoila/meho/pull/671?utm_source=github_walkthrough&utm_medium=github&utm_campaign=change_stack)

### CODE REVIEW

**Comment by damir-topic** [comment]
@coderabbitai review

**Comment by damir-topic** [comment]
## CI verification — both assigned regressions are fixed; one pre-existing unrelated flake is now exposed

**Green in CI:** DCO ✅ (real `Signed-off-by`, no admin bypass), `Go (golangci-lint + go test)` ✅ (Regression 1 fixed), `Python (ruff + mypy + pytest)` ✅, CodeRabbit ✅ (no actionable comments), CodeQL/Semgrep ✅.

**Regression 2 is proven fixed by the integration job's own log:**

- `main`'s CI at `796ebc0` (the commit this PR branches from): `1 failed, 16 passed` — **FAILED on `test_call_operation_about_dispatches_through_meta_tool`** with the exact `AttributeError: '_K3sTarget' object has no attribute 'get'`. Because the integration job runs `pytest -x` (fail-fast), the run stopped there.
- This PR's CI: `1 failed, **29** passed, 1 skipped` — that test now **passes** (CI log: `connector_resolved ... cls=KubernetesConnector product=k8s target_version=1.32.0 tie_break=specificity`, `kubernetes_api_client_built target=k3s-e2e`, `policy_gate_default_allow op_id=k8s.logs ... target_id=38b56d6a-... tenant_id=00000000-...a0a0`). The seeded tenant-scoped `Target` ORM row resolves end-to-end through `resolve_target` → dispatcher → live k3s. Net **+13 tests reached**.

### The remaining integration-job red is a pre-existing, unrelated flake this fix *exposed* (not caused)

`test_dispatch_logs_against_running_pod` fails with `connector_error: ApiException` on the **direct-`dispatch`** path (not the meta-tool target contract). It is a timing race: `k8s.logs` is called immediately after pod listing on a freshly-booted k3s, before pod logs are available, so the k8s API returns a raw `ApiException` instead of the expected `MultiContainerAmbiguityError`.

Why `main` CI didn't show it: `pytest -x` stopped at the meta-tool `AttributeError` (16 passed) and **never reached this test**. Fixing Regression 2 let the run proceed 13 tests further and surfaced this latent, pre-existing defect. It passes in isolation on clean `main`; it is **not** in this PR's changed surface (raw `dispatch`, unchanged); it is **not** one of the two assigned deterministic regressions.

Per surgical-changes discipline this is intentionally **not** fixed here — it is a separate, non-deterministic defect needing its own root-cause + wait-for-ready/retry fix and its own ticket. Flagging for a maintainer decision: a fully-green `main` for the v0.2.1 tag will need a follow-up addressing `test_dispatch_logs_against_running_pod`. This PR remains a strict net improvement and a prerequisite (it was masking that flake).

🤖 Generated with [Claude Code](https://claude.com/claude-code)
